import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: any[] = [
    {
      id:'1',
      name: 'Beef Pho',
      cookTime: '5-10',
      price: 15,
      favorite: true,
      origins: ['Northen'],
      stars: 4.5,
      imageUrl: 'assets/Pho_Bo.png',
      tags: ['beef', 'noodle soup'],
    },
    {
        id:'2',
        name: 'Chicken Pho',
        cookTime: '5-10',
        price: 14,
        favorite: false,
        origins: ['Northen'],
        stars: 4.5,
        imageUrl: 'assets/Pho_Ga.png',
        tags: ['chicken', 'noodle soup'],
      },
      {
        id:'3',
        name: 'Bun Bo Hue - Spicy beef noodle',
        cookTime: '5-10',
        price: 16,
        favorite: false,
        origins: ['Central'],
        stars: 4.5,
        imageUrl: 'assets/Bun_Bo_Hue.png',
        tags: ['beef', 'noodle soup', 'spicy'],
      },
      {
        id:'4',
        name: 'Broken rice - Com Tam',
        cookTime: '15-20',
        price: 17,
        favorite: false,
        origins: ['Southern'],
        stars: 4.5,
        imageUrl: 'assets/Com_Tam.png',
        tags: ['pork', 'rice'],
      },
      {
        id:'5',
        name: 'Banh Mi',
        cookTime: '10-15',
        price: 8,
        favorite: false,
        origins: ['Southern'],
        stars: 4.5,
        imageUrl: 'assets/Banh_Mi.png',
        tags: ['appetizer', 'bread', 'pork'],
      },
      {
        id:'6',
        name: 'Vietnamese coffee',
        cookTime: '5-10',
        price: 5,
        favorite: false,
        origins: ['Southern'],
        stars: 4.5,
        imageUrl: 'assets/Cafe_Sua_Da.png',
        tags: ['coffee', 'condensed milk'],
      },
      {
        id:'7',
        name: 'Egg coffee',
        cookTime: '10-15',
        price: 8,
        favorite: false,
        origins: ['Northern'],
        stars: 4.5,
        imageUrl: 'assets/Cafe_Trung.png',
        tags: ['coffee', 'egg', 'condensed milk'],
      },
      {
        id:'8',
        name: 'Goi Cuon - Salad Roll',
        cookTime: '10-15',
        price: 8,
        favorite: false,
        origins: ['Southern'],
        stars: 4.5,
        imageUrl: 'assets/Goi_Cuon.png',
        tags: ['shrimp', 'peanut sauce', 'appetizer'],
      },
      {
        id:'9',
        name: 'Banh Beo - rice steam cake',
        cookTime: '15-20',
        price: 10,
        favorite: false,
        origins: ['Northern'],
        stars: 4.5,
        imageUrl: 'assets/Banh_Beo_Chen.png',
        tags: ['shrimp', 'fish sauce', 'appetizer'],
      },
      {
        id:'10',
        name: 'Banh Bot Loc - Tapioca dumpling',
        cookTime: '15-20',
        price: 10,
        favorite: false,
        origins: ['Northern'],
        stars: 4.5,
        imageUrl: 'assets/Banh_Bot_Loc.png',
        tags: ['appetizer', 'shrimp', 'fish sauce'],
      },
]

export const sample_tags: any[] = [
  { name: 'All', count: 10 },
  { name: 'appetizer', count: 4 },
  { name: 'noodle soup', count: 3 },
  { name: 'shrimp', count: 2 },
  { name: 'fish sauce', count: 3 },
  { name: 'beef', count: 2},
  { name: 'pork', count: 2 },
  { name: 'chicken', count: 1 },
  { name: 'coffee', count: 2 },
  { name: 'egg', count: 1 },
  { name: 'rice', count: 1 },
  { name: 'bread', count: 1 },
  { name: 'spicy', count: 1 },
]

export const sample_users: any[] = [
  {
    name: "Hung Tran",
    email: "hung@gmail.com",
    password: "12345",
    address: "Vancouver BC",
    isAdmin: true,
  },
  {
    name: "Tram Dang",
    email: "tram@gmail.com",
    password: "12345",
    address: "Vancouver BC",
    isAdmin: false,
  }
]